name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codello/setup-lilypond@main
        with:
          lilypond-version: 2.24
      - name: Compile scores
        run: ./build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scores
          path: |
            output/*
