name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Build PDF
        uses: docker://jeandeaual/lilypond:2.24.3
        env:
            LANG: 'C.UTF-8'
        with:
          args: ./build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: |
            *.pdf
